- name: disable usb storage
  hosts: test
  become: true

  tasks:
    - name: 1.1.9 disable usb storage
      community.general.modprobe:
        name: usb-storage
        state: absent
        persistent: disabled
